// Generated by mau from Home.mau - do not edit.
// mau · Copyright (c) 2026 hexedmaya · mau License 1.0
import { signal, computed, effect, untracked, batch, onDestroy, router, route, navigate, h as __h, raw as __raw, each as __each, adoptStyle as __style } from "../../vendor/mau/index.js";
import Hero from "../components/Hero.js";
import Features from "../components/Features.js";

__style("@scope (.mau-7buxp2) {\n.how { padding: 3rem clamp(1rem, 4vw, 2.5rem); border-bottom: 2px solid var(--ink); }\r\n  .label { margin: 0 0 1.4rem; font-family: var(--mono); font-size: .8rem; font-weight: 700; text-transform: uppercase; letter-spacing: .14em; }\r\n  .steps { display: grid; grid-template-columns: repeat(auto-fit, minmax(15rem, 1fr)); border: 2px solid var(--ink); }\r\n  .step { padding: 1.2rem; border-right: 2px solid var(--ink); display: flex; flex-direction: column; }\r\n  .step:last-child { border-right: 0; }\r\n  @media (max-width: 760px) { .step { border-right: 0; border-bottom: 2px solid var(--ink); } .step:last-child { border-bottom: 0; } }\r\n  .num { margin: 0; font-size: 4rem; line-height: .9; font-weight: 900; letter-spacing: -.06em; color: var(--accent); }\r\n  .step h3 { margin: .4rem 0 .3rem; font-size: 1.4rem; letter-spacing: -.02em; }\r\n  .text { margin: 0 0 1rem; color: var(--mute); }\r\n  .code { margin: auto 0 0; padding: .9rem 1rem; overflow: auto; background: var(--ink); color: var(--paper); font: .8rem/1.6 var(--mono); }\r\n  .code code { font-family: inherit; }\r\n  .next { display: flex; flex-wrap: wrap; gap: 1rem 2rem; padding: 2.5rem clamp(1rem, 4vw, 2.5rem); }\r\n  .big {\r\n    font-size: clamp(1.6rem, 5vw, 2.6rem); font-weight: 900; letter-spacing: -.03em; color: var(--ink);\r\n    text-decoration: underline; text-decoration-thickness: 4px; text-underline-offset: .18em;\r\n  }\r\n  .big:hover { background: var(--accent); color: #000; text-decoration: none; }\n}");

export default function Home(props = {}) {
  const steps = [
    { n: "1", title: "write", text: "One .mau file: script, markup, style. Short, and it looks like HTML.", code: "<button on:click={inc}>\n  clicked {n()}\n</button>" },
    { n: "2", title: "compile", text: "One command on your machine. You get plain JavaScript next to each file.", code: "node mau/compiler/cli.js src" },
    { n: "3", title: "ship", text: "Commit the output. The browser loads ES modules, nobody needs a build.", code: "<script type=\"module\"\n  src=\"main.js\"></script>" },
  ];
  const __root = __h("div", { "class": "home" }, Hero({  }), __h("section", { "class": "how" }, __h("h2", { "class": "label" }, "how it works"), __h("div", { "class": "steps" }, __each(() => (steps), (s) => (s.n), (s) => [__h("div", { "class": "step" }, __h("p", { "class": "num" }, () => (s.n)), __h("h3", {  }, () => (s.title)), __h("p", { "class": "text" }, () => (s.text)), __h("pre", { "class": "code" }, __h("code", {  }, () => (s.code))))], true))), Features({  }), __h("div", { "class": "next" }, __h("a", { "class": "big", "href": "/start" }, "start here →"), __h("a", { "class": "big", "href": "/try" }, "try it →")));
  __root.classList.add("mau-7buxp2");
  return __root;
}
