// Generated by mau from Footer.mau - do not edit.
// mau · Copyright (c) 2026 hexedmaya · mau License 1.0
import { signal, computed, effect, untracked, batch, onDestroy, router, route, navigate, h as __h, raw as __raw, each as __each, adoptStyle as __style } from "../../vendor/mau/index.js";

__style("@scope (.mau-1cffsr) {\n:scope { border-top: 2px solid var(--ink); margin-top: 3rem; font-family: var(--mono); font-size: .85rem; }\r\n  .cols { display: flex; flex-wrap: wrap; justify-content: space-between; gap: 2rem; padding: 2rem clamp(1rem, 4vw, 2.5rem) 1.5rem; }\r\n  .brand { margin: 0; font-family: \"Helvetica Neue\", Arial, sans-serif; font-size: 3rem; font-weight: 900; letter-spacing: -.06em; line-height: 1; }\r\n  .brand i { color: var(--accent); font-style: normal; }\r\n  .tag { margin: .3rem 0 0; text-transform: uppercase; letter-spacing: .12em; color: var(--mute); }\r\n  .nav { display: flex; flex-wrap: wrap; gap: .4rem 1.5rem; align-self: flex-end; }\r\n  .nav a { color: var(--ink); text-decoration: underline; text-decoration-thickness: 2px; text-underline-offset: .22em; }\r\n  .nav a:hover { background: var(--accent); color: #000; text-decoration: none; }\r\n  .line { display: flex; flex-wrap: wrap; justify-content: space-between; gap: .5rem; padding: 1rem clamp(1rem, 4vw, 2.5rem) 2.5rem; border-top: 2px solid var(--ink); }\r\n  .line b { background: var(--accent); color: #000; padding: 0 .3em; }\r\n  .copy { color: var(--mute); }\n}");

export default function Footer(props = {}) {
  const __root = __h("footer", { "class": "foot" }, __h("div", { "class": "cols" }, __h("div", {  }, __h("p", { "class": "brand" }, "mau", __h("i", {  }, ".")), __h("p", { "class": "tag" }, "Make A UI.")), __h("nav", { "class": "nav" }, __h("a", { "href": "#/docs" }, "docs"), __h("a", { "href": "#/start" }, "getting started"), __h("a", { "href": "#/try" }, "try"), __h("a", { "href": "#/about" }, "about"), __h("a", { "href": "#/brand" }, "brand"))), __h("div", { "class": "line" }, __h("span", {  }, "mau, by ", __h("b", {  }, "hexedmaya")), __h("span", { "class": "copy" }, "© 2026 hexedmaya")));
  __root.classList.add("mau-1cffsr");
  return __root;
}
